package es.documentum.pantalla;

import com.documentum.fc.client.IDfSysObject;
import com.documentum.fc.client.IDfVersionPolicy;
import com.documentum.fc.common.DfException;
import com.documentum.fc.common.DfId;
import es.documentum.utilidades.Utilidades;
import java.util.ArrayList;
import javax.swing.JFileChooser;

public class PantallaCheckin extends javax.swing.JDialog {

    private String fichero = "";
    private String r_object_id = "";
    private String boton = "N";
    private String version = "";
    private String etiqueta="";
    private String descripcion="";
    private Boolean indexar=true;

    public Boolean getIndexar() {
        return indexar;
    }

    public void setIndexar(Boolean indexar) {
        this.indexar = indexar;
    }

    public String getEtiqueta() {
        return etiqueta;
    }

    public void setEtiqueta(String etiqueta) {
        this.etiqueta = etiqueta;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getFichero() {
        return fichero;
    }

    public void setFichero(String fichero) {
        this.fichero = fichero;
    }

    public String getR_object_id() {
        return r_object_id;
    }

    public void setR_object_id(String r_object_id) {
        this.r_object_id = r_object_id;
    }

    public void setLabelFichero(String fichero) {
        this.labelFichero.setText(fichero);
    }

    public static PantallaDocumentum ventanapadre = null;

    public PantallaCheckin(PantallaDocumentum parent, boolean modal) {
        super(parent, modal);
        ventanapadre = parent;
        initComponents();
        setLocationRelativeTo(ventanapadre);
    }

    public boolean respuesta() {
        return (boton.equals("S"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupmenu = new javax.swing.JPopupMenu();
        opcionPegar = new javax.swing.JMenuItem();
        botonAceptar = new javax.swing.JButton();
        labelFichero = new javax.swing.JLabel();
        textoVersion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textoFichero = new javax.swing.JTextField();
        botonCancelar = new javax.swing.JButton();
        etiquetaPanel = new javax.swing.JLabel();
        botonNavegar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        checkMisma = new javax.swing.JRadioButton();
        checkMenor = new javax.swing.JRadioButton();
        checkMayor = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textoDescripcion = new javax.swing.JTextField();
        labelVersion = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        labelFormato = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        checkIndexar = new javax.swing.JCheckBox();

        opcionPegar.setText("Pegar");
        opcionPegar.setToolTipText("Pegar");
        opcionPegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionPegarActionPerformed(evt);
            }
        });
        popupmenu.add(opcionPegar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/documentum/imagenes/si.png"))); // NOI18N
        botonAceptar.setMnemonic('A');
        botonAceptar.setText("OK");
        botonAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAceptar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botonAceptar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        labelFichero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelFichero.setMaximumSize(new java.awt.Dimension(41, 22));
        labelFichero.setMinimumSize(new java.awt.Dimension(41, 22));
        labelFichero.setPreferredSize(new java.awt.Dimension(41, 22));

        textoVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoVersionActionPerformed(evt);
            }
        });

        jLabel2.setText("Check In desde fichero");

        textoFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoFicheroActionPerformed(evt);
            }
        });

        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/documentum/imagenes/no.png"))); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCancelar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botonCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        etiquetaPanel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiquetaPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        etiquetaPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiquetaPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiquetaPanelMouseEntered(evt);
            }
        });

        botonNavegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/documentum/imagenes/carpeta.png"))); // NOI18N
        botonNavegar.setToolTipText("Seleccionar directorio de destino");
        botonNavegar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonNavegar.setMaximumSize(new java.awt.Dimension(25, 25));
        botonNavegar.setMinimumSize(new java.awt.Dimension(25, 25));
        botonNavegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNavegarActionPerformed(evt);
            }
        });

        jLabel3.setText("Guardar como:");

        checkMisma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMismaActionPerformed(evt);
            }
        });

        checkMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMenorActionPerformed(evt);
            }
        });

        checkMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMayorActionPerformed(evt);
            }
        });

        jLabel4.setText("Etiqueta de versión: ");

        jLabel5.setText("Descripción:");

        textoDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDescripcionActionPerformed(evt);
            }
        });

        labelVersion.setMaximumSize(new java.awt.Dimension(18, 198));
        labelVersion.setMinimumSize(new java.awt.Dimension(18, 198));
        labelVersion.setPreferredSize(new java.awt.Dimension(18, 198));

        labelTipo.setMaximumSize(new java.awt.Dimension(18, 198));
        labelTipo.setMinimumSize(new java.awt.Dimension(18, 198));
        labelTipo.setPreferredSize(new java.awt.Dimension(18, 198));

        labelFormato.setMaximumSize(new java.awt.Dimension(18, 198));
        labelFormato.setMinimumSize(new java.awt.Dimension(18, 198));
        labelFormato.setPreferredSize(new java.awt.Dimension(18, 198));

        jLabel1.setText("(misma versión)");
        jLabel1.setMaximumSize(new java.awt.Dimension(75, 21));
        jLabel1.setMinimumSize(new java.awt.Dimension(75, 21));
        jLabel1.setPreferredSize(new java.awt.Dimension(75, 21));

        jLabel6.setText("(versión menor)");
        jLabel6.setMaximumSize(new java.awt.Dimension(76, 21));
        jLabel6.setMinimumSize(new java.awt.Dimension(76, 21));
        jLabel6.setPreferredSize(new java.awt.Dimension(76, 21));

        jLabel7.setText("(versión mayor)");
        jLabel7.setMaximumSize(new java.awt.Dimension(76, 21));
        jLabel7.setMinimumSize(new java.awt.Dimension(76, 21));
        jLabel7.setPreferredSize(new java.awt.Dimension(76, 21));

        checkIndexar.setText("Indexar documento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(etiquetaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(checkMisma)
                                            .addComponent(checkMenor)
                                            .addComponent(checkMayor))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(textoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(labelFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(textoFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(botonNavegar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(labelFormato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                        .addComponent(labelTipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelVersion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(checkIndexar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelFichero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFormato, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkMisma, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(checkMenor))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkMayor)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(checkIndexar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoFichero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNavegar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAceptar)
                    .addComponent(botonCancelar))
                .addGap(18, 18, 18)
                .addComponent(etiquetaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {textoFichero, textoVersion});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botonAceptar, botonCancelar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        if (comprobarValores()) {
            boton = "S";
            this.dispose();
        }

    }//GEN-LAST:event_botonAceptarActionPerformed

    private void textoVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoVersionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoVersionActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        boton = "N";
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void etiquetaPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaPanelMouseEntered
        etiquetaPanel.setToolTipText(etiquetaPanel.getText());
    }//GEN-LAST:event_etiquetaPanelMouseEntered

    private void opcionPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionPegarActionPerformed
        if (evt.getSource().toString().equals("textoRutaSO")) {
            textoFichero.setText(Utilidades.pegarTextoPortapapeles());
        }
        if (evt.getSource().toString().equals("textoCarpeta")) {
            textoVersion.setText(Utilidades.pegarTextoPortapapeles());
        }
    }//GEN-LAST:event_opcionPegarActionPerformed

    private void etiquetaPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaPanelMouseClicked
        if (evt.getClickCount() == 2 && evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
            Utilidades.copiarTextoPortapapeles(etiquetaPanel.getText());
        }
    }//GEN-LAST:event_etiquetaPanelMouseClicked

    private void textoFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoFicheroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoFicheroActionPerformed

    private void botonNavegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNavegarActionPerformed
        JFileChooser fc = new JFileChooser("");
        fc.setCurrentDirectory(new java.io.File("."));
        fc.setDialogTitle("Fichero");
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setAcceptAllFileFilterUsed(false);

        int x = fc.showOpenDialog(this);
        if (x == JFileChooser.CANCEL_OPTION || x == JFileChooser.ERROR_OPTION) {
            return;
        }
        String rutalocal = fc.getSelectedFile().getPath();
        if (!rutalocal.isEmpty()) {
            textoFichero.setText(rutalocal);
        }
    }//GEN-LAST:event_botonNavegarActionPerformed

    private void textoDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDescripcionActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        inicializar();
    }//GEN-LAST:event_formComponentShown

    private void checkMismaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMismaActionPerformed
        checkMisma.setSelected(true);
        checkMenor.setSelected(false);
        checkMayor.setSelected(false);
    }//GEN-LAST:event_checkMismaActionPerformed

    private void checkMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMenorActionPerformed
        checkMisma.setSelected(false);
        checkMenor.setSelected(true);
        checkMayor.setSelected(false);
    }//GEN-LAST:event_checkMenorActionPerformed

    private void checkMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMayorActionPerformed
        checkMisma.setSelected(false);
        checkMenor.setSelected(false);
        checkMayor.setSelected(true);
    }//GEN-LAST:event_checkMayorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PantallaCheckin dialog = new PantallaCheckin(ventanapadre, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setLocationRelativeTo(ventanapadre);
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonNavegar;
    private javax.swing.JCheckBox checkIndexar;
    private javax.swing.JRadioButton checkMayor;
    private javax.swing.JRadioButton checkMenor;
    private javax.swing.JRadioButton checkMisma;
    private javax.swing.JLabel etiquetaPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelFichero;
    private javax.swing.JLabel labelFormato;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JLabel labelVersion;
    private javax.swing.JMenuItem opcionPegar;
    private javax.swing.JPopupMenu popupmenu;
    private javax.swing.JTextField textoDescripcion;
    private javax.swing.JTextField textoFichero;
    private javax.swing.JTextField textoVersion;
    // End of variables declaration//GEN-END:variables

    public void asignariconos() {
    }

    private Boolean comprobarValores() {
        Boolean resultado = true;

        if (checkMisma.isSelected()) {
            setVersion("igual");
        } else if (checkMenor.isSelected()) {
            setVersion("menor");
        } else if (checkMayor.isSelected()) {
            setVersion("mayor");
        }
        
        if (!textoVersion.getText().isEmpty()) {
            setEtiqueta(textoVersion.getText());
        }
        if (!textoDescripcion.getText().isEmpty()) {
            setDescripcion(textoDescripcion.getText());
        }

        setIndexar(checkIndexar.isSelected());
        
        return resultado;
    }

    private void inicializar() {
        if (!r_object_id.isEmpty()) {
            ArrayList formato = ventanapadre.utilDocum.dameAtributo(r_object_id, "r_object_type");
            ArrayList tipo = ventanapadre.utilDocum.dameAtributo(r_object_id, "a_content_type");
            ArrayList version = ventanapadre.utilDocum.dameAtributo(r_object_id, "r_version_label");
            String versionactual = version.get(0).toString();
            String valversion[] = versionactual.split("\\.");
            String mayor = valversion[0];
            String menor = valversion[1];
            String versionmayor = String.valueOf(Integer.parseInt(mayor) + 1) + ".0";
            String versionmenor = mayor + "." + String.valueOf(Integer.parseInt(menor) + 1);
            
            try {
                IDfSysObject sysObject = (IDfSysObject) ventanapadre.utilDocum.conectarDocumentum().getObject(new DfId(r_object_id));
                IDfVersionPolicy vp = sysObject.getVersionPolicy();
                versionactual=vp.getSameLabel();
                versionmayor=vp.getNextMajorLabel();
                versionmenor=vp.getNextMinorLabel();
            } catch (DfException ex) {
                Utilidades.escribeLog("Error al obtener versión en el Chek In. Error: "+ ex.getMessage());
            }

            checkMisma.setText(versionactual);
            checkMenor.setText(versionmenor);
            checkMayor.setText(versionmayor);
            checkMisma.setSelected(true);
            checkMenor.setSelected(false);
            checkMayor.setSelected(false);
            labelVersion.setText("Versión: " + versionactual + ", Current");
            labelTipo.setText("Tipo: " + tipo.get(0));
            labelFormato.setText("Formato: " + formato.get(0));
            checkIndexar.setSelected(getIndexar());
        }
    }

}
