package es.documentum.pantalla;

import com.lgooddatepicker.core.DatePickerSettings;
import com.lgooddatepicker.optionalusertools.DateUtilities;
import es.documentum.utilidades.Utilidades;
import java.text.ParsePosition;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

public class PantallaPedirFechas extends javax.swing.JDialog {

    public String fechainicial = "";
    public String fechafinal = "";
    public String correo = "";
    public Boolean respuesta = false;

    public Boolean getRespuesta() {
        return respuesta;
    }

    public void setRespuesta(Boolean respuesta) {
        this.respuesta = respuesta;
    }

    public static PantallaDocumentum ventanapadre = null;

    public String getFechainicial() {
        return fechainicial;
    }

    public String getFechafinal() {
        return fechafinal;
    }

    public void setFechainicial(String valor) {
        fechainicial = valor;
    }

    public void setFechafinal(String valor) {
        fechafinal = valor;
    }

    public String getCorreo() {
        return correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    public PantallaPedirFechas(PantallaDocumentum parent, boolean modal) {
        super(parent, modal);
        ventanapadre = parent;
        initComponents();
        setLocationRelativeTo(ventanapadre);
        inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        etiquetaPanel = new javax.swing.JLabel();
        dPFechaInicio = new com.lgooddatepicker.core.DatePicker();
        dPFechaFin = new com.lgooddatepicker.core.DatePicker();
        jLabel3 = new javax.swing.JLabel();
        textoCorreo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/documentum/imagenes/si.png"))); // NOI18N
        botonAceptar.setMnemonic('A');
        botonAceptar.setText("Aceptar");
        botonAceptar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botonAceptar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botonAceptar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha de Inicio");
        jLabel1.setMaximumSize(new java.awt.Dimension(41, 22));
        jLabel1.setMinimumSize(new java.awt.Dimension(41, 22));
        jLabel1.setPreferredSize(new java.awt.Dimension(41, 22));

        jLabel2.setText("Fecha de Destino");

        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/documentum/imagenes/no.png"))); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        botonCancelar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botonCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        etiquetaPanel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiquetaPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        etiquetaPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiquetaPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiquetaPanelMouseEntered(evt);
            }
        });

        dPFechaInicio.setToolTipText("Fecha de Inicio");

        jLabel3.setText("Email");
        jLabel3.setMaximumSize(new java.awt.Dimension(34, 24));
        jLabel3.setMinimumSize(new java.awt.Dimension(34, 24));
        jLabel3.setPreferredSize(new java.awt.Dimension(34, 24));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(etiquetaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                .addGap(2, 2, 2))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoCorreo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonAceptar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dPFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dPFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCancelar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dPFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dPFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(etiquetaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        if (comprobarValores()) {
            setFechafinal(dPFechaFin.getText());
            setFechainicial(dPFechaInicio.getText());
            setCorreo(textoCorreo.getText());
            setRespuesta(true);
            this.dispose();
        }

    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        setRespuesta(false);
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void etiquetaPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaPanelMouseEntered
        etiquetaPanel.setToolTipText(etiquetaPanel.getText());
    }//GEN-LAST:event_etiquetaPanelMouseEntered

    private void etiquetaPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaPanelMouseClicked
        if (evt.getClickCount() == 2 && evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
            Utilidades.copiarTextoPortapapeles(etiquetaPanel.getText());
        }
    }//GEN-LAST:event_etiquetaPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PantallaPedirFechas dialog = new PantallaPedirFechas(ventanapadre, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setLocationRelativeTo(ventanapadre);
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private com.lgooddatepicker.core.DatePicker dPFechaFin;
    private com.lgooddatepicker.core.DatePicker dPFechaInicio;
    private javax.swing.JLabel etiquetaPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField textoCorreo;
    // End of variables declaration//GEN-END:variables

    public void asignariconos() {
    }

    private Boolean comprobarValores() {
        Boolean resultado = true;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date fecha1 = sdf.parse(dPFechaInicio.getText(), new ParsePosition(0));
        Calendar cal1 = new GregorianCalendar();
        cal1.setTime(fecha1);
        Date fecha2 = sdf.parse(dPFechaFin.getText(), new ParsePosition(0));
        Calendar cal2 = new GregorianCalendar();
        cal2.setTime(fecha2);

        // Comparaciones
        if (cal2.before(cal1)) {
            etiquetaPanel.setText(" La fecha final no puede ser anterior a la fecha inicial");
            resultado = false;
            dPFechaInicio.setText("");
            dPFechaFin.setText("");
        }

        return resultado;
    }

    private void inicializar() {
        DatePickerSettings settings = dPFechaInicio.getSettings();
        settings.initialDate = LocalDate.now();
        settings.formatDatesCommonEra = DateUtilities.createFormatterFromPatternString(
                "dd/MM/yyyy", settings.pickerLocale);
        settings.formatDatesBeforeCommonEra = DateUtilities.createFormatterFromPatternString(
                "dd/MM/yyyy", settings.pickerLocale);

        settings = dPFechaFin.getSettings();
        settings.initialDate = LocalDate.now();
        settings.formatDatesCommonEra = DateUtilities.createFormatterFromPatternString(
                "dd/MM/yyyy", settings.pickerLocale);
        settings.formatDatesBeforeCommonEra = DateUtilities.createFormatterFromPatternString(
                "dd/MM/yyyy", settings.pickerLocale);
    }
}
