/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package es.documentum.pantalla;

import com.documentum.fc.client.IDfCollection;
import com.documentum.fc.client.IDfFolder;
import com.documentum.fc.client.IDfTypedObject;
import com.documentum.fc.common.DfException;
import com.documentum.fc.common.IDfValue;
import es.documentum.utilidades.ClassPathUpdater;
import es.documentum.utilidades.Utilidades;
import es.documentum.utilidades.UtilidadesDocumentum;
import static es.documentum.utilidades.UtilidadesDocumentum.getDfObjectValue;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author julian.collado
 */
public class PantallaImportar extends javax.swing.JFrame {

    Utilidades util = new Utilidades();
    PantallaBarra barradocum = null;
    Boolean botonderecho = false;
    String componente = "";
    String tipodocumental = "dm_document";
    UtilidadesDocumentum utilidadesdocumentum;
    String dirSSOO = "";
    String rutadcm;

    public String getRutadcm() {
        return this.TextoCarpetaDocumentum.getText();
    }

    public void setRutadcm(String rutadcm) {
        this.TextoCarpetaDocumentum.setText(rutadcm);
    }
    public static PantallaDocumentum ventanapadre = null;

    public PantallaImportar(PantallaDocumentum parent, boolean modal) {
        ventanapadre = parent;
        initComponents();
        try {
            setIconImage(new ImageIcon(getLogo()).getImage());
        } catch (NullPointerException e) {
            Utilidades.escribeLog("\nError cargando el Logo " + e.getMessage() + "\n");
        }
        inicializar();
        setLocationRelativeTo(null);
        cargarComboTipos();
    }

    private void inicializar() {
        String dirdfc = util.usuarioHome() + util.separador() + "documentumdcfs" + util.separador() + "documentum" + util.separador() + "shared" + util.separador();
        try {
            ClassPathUpdater.add(dirdfc);
            ClassPathUpdater.add(dirdfc + "lib" + util.separador() + "jsafeFIPS.jar");
        } catch (IOException | IllegalAccessException | NoSuchMethodException | InvocationTargetException ex) {
            Utilidades.escribeLog("Error al actualizar el Classpath  - Error: " + ex.getMessage());
        }
        utilidadesdocumentum = new UtilidadesDocumentum(dirdfc + "dfc.properties");
        RBFichero.setSelected(true);
    }

    protected static Image getLogo() {
        java.net.URL imgURL = PantallaDocumentum.class.getClassLoader().getResource("es/documentum/imagenes/documentum_logo.jpg");
        if (imgURL != null) {
            return new ImageIcon(imgURL).getImage();
        } else {
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupEditar = new javax.swing.JPopupMenu();
        opcionCopiar = new javax.swing.JMenuItem();
        opcionPegar = new javax.swing.JMenuItem();
        popupDatos = new javax.swing.JPopupMenu();
        opcionCopiarValor = new javax.swing.JMenuItem();
        opcionExportarExcel = new javax.swing.JMenuItem();
        popupHistorial = new javax.swing.JPopupMenu();
        opcionVaciarHistorial = new javax.swing.JMenuItem();
        panelImportar = new javax.swing.JPanel();
        LabelFicheroImportar = new javax.swing.JLabel();
        comboTipoDocumental = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextoFichero = new javax.swing.JTextField();
        TextoCarpetaDocumentum = new javax.swing.JTextField();
        botonSelFichero = new javax.swing.JButton();
        LabelNombreFichero = new javax.swing.JLabel();
        TextoNombreFichero = new javax.swing.JTextField();
        RBFichero = new javax.swing.JRadioButton();
        RBDirectorio = new javax.swing.JRadioButton();
        panelEstado = new javax.swing.JPanel();
        textoLog = new javax.swing.JTextField();
        botonEjecutar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        opciones = new javax.swing.JMenu();
        opcionEjecutar = new javax.swing.JMenuItem();
        opcionSalir = new javax.swing.JMenuItem();

        opcionCopiar.setText("Copiar Ctrl+C");
        opcionCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionCopiarActionPerformed(evt);
            }
        });
        popupEditar.add(opcionCopiar);

        opcionPegar.setText("Pegar  Ctrl+V");
        opcionPegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionPegarActionPerformed(evt);
            }
        });
        popupEditar.add(opcionPegar);

        opcionCopiarValor.setText("Copiar Valor");
        opcionCopiarValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionCopiarValorActionPerformed(evt);
            }
        });
        popupDatos.add(opcionCopiarValor);

        opcionExportarExcel.setText("Exportar a Excel");
        opcionExportarExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionExportarExcelActionPerformed(evt);
            }
        });
        popupDatos.add(opcionExportarExcel);

        opcionVaciarHistorial.setText("Vaciar Historial de DQL");
        opcionVaciarHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionVaciarHistorialActionPerformed(evt);
            }
        });
        popupHistorial.add(opcionVaciarHistorial);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Importar Archivos a Documentum");
        setMaximumSize(new java.awt.Dimension(565, 307));
        setMinimumSize(new java.awt.Dimension(565, 307));
        setResizable(false);

        panelImportar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LabelFicheroImportar.setText("Fichero a Importar");

        comboTipoDocumental.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                comboTipoDocumentalMousePressed(evt);
            }
        });
        comboTipoDocumental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoDocumentalActionPerformed(evt);
            }
        });

        jLabel3.setText("Carpeta destino en Documentum");

        jLabel4.setText("Tipo Documental Documentum");

        TextoFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoFicheroActionPerformed(evt);
            }
        });

        botonSelFichero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/documentum/imagenes/carpeta.png"))); // NOI18N
        botonSelFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSelFicheroActionPerformed(evt);
            }
        });

        LabelNombreFichero.setText("Nombre del fichero");

        TextoNombreFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoNombreFicheroActionPerformed(evt);
            }
        });

        RBFichero.setText("Fichero");
        RBFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBFicheroActionPerformed(evt);
            }
        });

        RBDirectorio.setText("Directorio");
        RBDirectorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBDirectorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImportarLayout = new javax.swing.GroupLayout(panelImportar);
        panelImportar.setLayout(panelImportarLayout);
        panelImportarLayout.setHorizontalGroup(
            panelImportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImportarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelImportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TextoCarpetaDocumentum)
                        .addComponent(comboTipoDocumental, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelImportarLayout.createSequentialGroup()
                            .addGroup(panelImportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(panelImportarLayout.createSequentialGroup()
                                    .addComponent(LabelFicheroImportar, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(53, 53, 53)
                                    .addComponent(RBFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(RBDirectorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(TextoFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botonSelFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LabelNombreFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoNombreFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );
        panelImportarLayout.setVerticalGroup(
            panelImportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImportarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelFicheroImportar)
                    .addComponent(RBFichero)
                    .addComponent(RBDirectorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextoFichero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSelFichero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(LabelNombreFichero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoNombreFichero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoCarpetaDocumentum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboTipoDocumental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelEstado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textoLog.setEditable(false);
        textoLog.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        textoLog.setForeground(new java.awt.Color(0, 51, 204));
        textoLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textoLogMousePressed(evt);
            }
        });
        textoLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEstadoLayout = new javax.swing.GroupLayout(panelEstado);
        panelEstado.setLayout(panelEstadoLayout);
        panelEstadoLayout.setHorizontalGroup(
            panelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoLog, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelEstadoLayout.setVerticalGroup(
            panelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoLog, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        botonEjecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/documentum/imagenes/ejecutar_peq.png"))); // NOI18N
        botonEjecutar.setText("Ejecutar");
        botonEjecutar.setMaximumSize(new java.awt.Dimension(100, 40));
        botonEjecutar.setMinimumSize(new java.awt.Dimension(100, 40));
        botonEjecutar.setPreferredSize(new java.awt.Dimension(100, 40));
        botonEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEjecutarActionPerformed(evt);
            }
        });

        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/documentum/imagenes/salir_peq.png"))); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.setMaximumSize(new java.awt.Dimension(100, 40));
        botonSalir.setMinimumSize(new java.awt.Dimension(100, 40));
        botonSalir.setPreferredSize(new java.awt.Dimension(100, 40));
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        opciones.setText("Opciones");

        opcionEjecutar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        opcionEjecutar.setText("Ejecutar");
        opcionEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionEjecutarActionPerformed(evt);
            }
        });
        opciones.add(opcionEjecutar);

        opcionSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        opcionSalir.setText("Salir");
        opcionSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionSalirActionPerformed(evt);
            }
        });
        opciones.add(opcionSalir);

        jMenuBar1.add(opciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(botonEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 403, Short.MAX_VALUE)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(panelImportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonEjecutar, botonSalir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelImportar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botonEjecutar, botonSalir});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importarDirectorio() {
        new Thread() {
            public void run() {
                PantallaImportar.this.dirSSOO = PantallaImportar.this.TextoFichero.getText();
                PantallaImportar.this.panelImportar.setEnabled(false);
                PantallaImportar.this.botonEjecutar.setEnabled(false);
                PantallaImportar.this.botonSalir.setEnabled(false);
                PantallaImportar.this.opcionEjecutar.setEnabled(false);
                PantallaImportar.this.opcionSalir.setEnabled(false);
                PantallaImportar.this.barradocum = new PantallaBarra(PantallaImportar.this, false);
                PantallaImportar.this.barradocum.setTitle("Importando en Documentum ...");
                PantallaBarra.barra.setIndeterminate(true);
                PantallaImportar.this.barradocum.botonParar.setVisible(true);
                PantallaImportar.this.barradocum.setLabelMensa("");
                PantallaBarra.barra.setOpaque(true);
                PantallaBarra.barra.setStringPainted(false);
                PantallaImportar.this.barradocum.validate();
                PantallaImportar.this.barradocum.setVisible(true);
                PantallaImportar.this.ImportarDirEnDcm(PantallaImportar.this.dirSSOO);
                PantallaImportar.this.panelImportar.setEnabled(true);
                PantallaImportar.this.botonEjecutar.setEnabled(true);
                PantallaImportar.this.botonSalir.setEnabled(true);
                PantallaImportar.this.opcionEjecutar.setEnabled(true);
                PantallaImportar.this.opcionSalir.setEnabled(true);
                PantallaImportar.this.barradocum.dispose();
                PantallaImportar.ventanapadre.BuscarEnDocumentum();
                PantallaImportar.this.dispose();
            }
        }.start();
    }


    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        salir();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEjecutarActionPerformed
        if (ComprobarValores()) {
            if (this.RBFichero.isSelected()) {
                subirADocumentum();
            } else {
                importarDirectorio();
            }
        }
    }//GEN-LAST:event_botonEjecutarActionPerformed

    private void opcionEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionEjecutarActionPerformed
        if (ComprobarValores()) {
            if (this.RBFichero.isSelected()) {
                subirADocumentum();
            } else {
                importarDirectorio();
            }
        }
    }//GEN-LAST:event_opcionEjecutarActionPerformed

    private void opcionSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionSalirActionPerformed
        salir();
    }//GEN-LAST:event_opcionSalirActionPerformed

    private void opcionCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionCopiarActionPerformed
        if (componente.equals("textoLog")) {
            if (textoLog.getSelectedText() == null) {
                Utilidades.copiarTextoPortapapeles(textoLog.getText());
            } else {
                Utilidades.copiarTextoPortapapeles(textoLog.getSelectedText());
            }
        }
    }//GEN-LAST:event_opcionCopiarActionPerformed

    private void opcionPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionPegarActionPerformed
    }//GEN-LAST:event_opcionPegarActionPerformed

    private void opcionCopiarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionCopiarValorActionPerformed

    }//GEN-LAST:event_opcionCopiarValorActionPerformed

    private void opcionExportarExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionExportarExcelActionPerformed

    }//GEN-LAST:event_opcionExportarExcelActionPerformed

    private void comboTipoDocumentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoDocumentalActionPerformed
        tipodocumental = (String) comboTipoDocumental.getSelectedItem();

    }//GEN-LAST:event_comboTipoDocumentalActionPerformed

    private void comboTipoDocumentalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboTipoDocumentalMousePressed

    }//GEN-LAST:event_comboTipoDocumentalMousePressed

    private void opcionVaciarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionVaciarHistorialActionPerformed

    }//GEN-LAST:event_opcionVaciarHistorialActionPerformed

    private void TextoFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoFicheroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoFicheroActionPerformed

    private void botonSelFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSelFicheroActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("/"));
        if (RBFichero.isSelected()) {
            chooser.setDialogTitle("Seleccionar fichero a importar");
            chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                TextoFichero.setText(chooser.getSelectedFile().toString());
                TextoNombreFichero.setText(chooser.getSelectedFile().getName());
            } else {
                Utilidades.escribeLog("No se ha seleccionado el fichero de salida ");
            }
        } else {
            chooser.setDialogTitle("Seleccionar Directorio a importar");
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                TextoFichero.setText(chooser.getSelectedFile().toString());
            } else {
                Utilidades.escribeLog("No se ha seleccionado el directorio a importar");
            }
        }
    }//GEN-LAST:event_botonSelFicheroActionPerformed

    private void TextoNombreFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoNombreFicheroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoNombreFicheroActionPerformed

    private void textoLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoLogActionPerformed

    private void textoLogMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoLogMousePressed
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON3) {
            botonderecho = true;
            componente = "textoLog";
            popupmenu(evt);
        }

    }//GEN-LAST:event_textoLogMousePressed

    private void RBDirectorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBDirectorioActionPerformed
        RBFichero.setSelected(false);
        LabelFicheroImportar.setText("Directorio a Importar");
        LabelNombreFichero.setEnabled(false);
        TextoNombreFichero.setEnabled(false);
    }//GEN-LAST:event_RBDirectorioActionPerformed

    private void RBFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBFicheroActionPerformed
        RBDirectorio.setSelected(false);
        LabelFicheroImportar.setText("Fichero a Importar");
        LabelNombreFichero.setEnabled(true);
        TextoNombreFichero.setEnabled(true);
    }//GEN-LAST:event_RBFicheroActionPerformed

    private void popupmenu(MouseEvent evt) {
        if (evt.isPopupTrigger() || botonderecho) {
            botonderecho = false;

            if (evt.getSource() == textoLog) {
                opcionPegar.setEnabled(false);
                popupEditar.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }

    private Boolean ComprobarValores() {
        Boolean correcto = true;

        if (RBFichero.isSelected()) {
            if (TextoFichero.getText().isEmpty()) {
                textoLog.setText("Debe indicar el fichero a importar");
                TextoFichero.requestFocus();
                return false;
            }

            if (TextoNombreFichero.getText().isEmpty()) {
                textoLog.setText("Debe indicar un nombre de fichero");
                TextoNombreFichero.requestFocus();
                return false;
            }
        } else {
            if (TextoFichero.getText().isEmpty()) {
                textoLog.setText("Debe indicar el directorio del Sistema Operativo a importar");
                TextoFichero.requestFocus();
                return false;
            }
        }

        if (TextoCarpetaDocumentum.getText().isEmpty()) {
            textoLog.setText("Debe indicar una carpeta de destino en Documentum");
            TextoCarpetaDocumentum.requestFocus();
            return false;
        }

        if (ventanapadre.utilDocum.existeCarpeta(TextoCarpetaDocumentum.getText()) == false) {
            textoLog.setText("La carpeta indicada parece que no existe en Documentum");
            TextoCarpetaDocumentum.requestFocus();
            return false;
        }
        return correcto;
    }

    private void cargarComboTipos() {
        ArrayList comboBoxItems = new ArrayList();
        String dirdfc = util.usuarioHome() + util.separador() + "documentumdcfs" + util.separador() + "documentum" + util.separador() + "shared" + util.separador();
        try {
            ClassPathUpdater.add(dirdfc);
            ClassPathUpdater.add(dirdfc + "lib" + util.separador() + "jsafeFIPS.jar");
        } catch (IOException | IllegalAccessException | NoSuchMethodException | InvocationTargetException ex) {
            Utilidades.escribeLog("Error al actualizar el Classpath  - Error: " + ex.getMessage());
        }
        UtilidadesDocumentum utildocum = new UtilidadesDocumentum(dirdfc + "dfc.properties");
        int posicion = 0;

        try {
            //            IDfCollection col = utildocum.ejecutarDql("select name from dm_type where  super_name in ('dm_document') or name in ('dm_document') order by name");
            IDfCollection col = utildocum.ejecutarDql("select name from dm_type order by name");
            if (!utildocum.dameError().equals("")) {
                textoLog.setText(utildocum.dameError());
                barradocum.dispose();
                return;
            }

            while (col.next()) {
                IDfTypedObject row = (IDfTypedObject) col.getTypedObject();
                IDfValue attrValue = row.getValue("name");
                comboBoxItems.add(getDfObjectValue(attrValue));
                if (getDfObjectValue(attrValue).equals("dm_document")) {
                    posicion = comboBoxItems.size() - 1;
                }
            }

            col.close();

        } catch (DfException e) {
            textoLog.setText("Error - " + e.getMessage());
        }

        DefaultComboBoxModel modelo = new DefaultComboBoxModel(comboBoxItems.toArray());
        comboTipoDocumental.setModel(modelo);
        comboTipoDocumental.setSelectedIndex(posicion);
    }

    public static void main(String args[]) {
        PantallaImportar panta = new PantallaImportar(ventanapadre, true);
        panta.TextoCarpetaDocumentum.setText("/dmadmin/prueba");
        panta.tipodocumental = "car_doc_trabajo_salida";
        panta.ImportarDirEnDcm("D:\\Adif\\Documentum\\D_A1_DCD");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaImportar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PantallaImportar(ventanapadre, true).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFicheroImportar;
    private javax.swing.JLabel LabelNombreFichero;
    private javax.swing.JRadioButton RBDirectorio;
    private javax.swing.JRadioButton RBFichero;
    private javax.swing.JTextField TextoCarpetaDocumentum;
    private javax.swing.JTextField TextoFichero;
    private javax.swing.JTextField TextoNombreFichero;
    private javax.swing.JButton botonEjecutar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonSelFichero;
    private javax.swing.JComboBox comboTipoDocumental;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem opcionCopiar;
    private javax.swing.JMenuItem opcionCopiarValor;
    private javax.swing.JMenuItem opcionEjecutar;
    private javax.swing.JMenuItem opcionExportarExcel;
    private javax.swing.JMenuItem opcionPegar;
    private javax.swing.JMenuItem opcionSalir;
    private javax.swing.JMenuItem opcionVaciarHistorial;
    private javax.swing.JMenu opciones;
    private javax.swing.JPanel panelEstado;
    private javax.swing.JPanel panelImportar;
    private javax.swing.JPopupMenu popupDatos;
    private javax.swing.JPopupMenu popupEditar;
    private javax.swing.JPopupMenu popupHistorial;
    private javax.swing.JTextField textoLog;
    // End of variables declaration//GEN-END:variables

    private void salir() {
        this.dispose();
    }

    private void subirADocumentum() {
        textoLog.setText(utilidadesdocumentum.importarADocumentum(TextoNombreFichero.getText(), TextoFichero.getText(), TextoCarpetaDocumentum.getText(), tipodocumental));
    }

   public void ImportarDirEnDcm(String rutaSO)
  {
    File dir = new File(rutaSO);
    File[] listFile = dir.listFiles();
    if (listFile != null) {
      for (int i = 0; i < listFile.length; i++)
      {
        String ruta = listFile[i].getPath().replace("\\", "/");
        String nombreDir = "";
        if (listFile[i].isDirectory())
        {
          String nueva = ruta.substring(this.dirSSOO.length() + 1, ruta.length());
          nombreDir = this.TextoCarpetaDocumentum.getText() + (nueva.equals("/") ? "" : new StringBuilder().append("/").append(nueva).toString());
          
          this.textoLog.setText("Creando carpeta " + nombreDir + " ... ");
          this.barradocum.setLabelMensa("Creando carpeta " + nombreDir + " ... ");
          IDfFolder folder = this.utilidadesdocumentum.crearCarpeta(nombreDir);
          this.textoLog.setText("Creada carpeta " + nombreDir);
          this.barradocum.setLabelMensa("Creada carpeta " + nombreDir);
          this.panelEstado.repaint();
          ImportarDirEnDcm(listFile[i].getPath().replace("\\", "/"));
        }
        else
        {
          String nombre = listFile[i].getName().replace("\\", "/");
          String nueva = ruta.substring(this.dirSSOO.length() + 1, ruta.length() - nombre.length());
          nueva = nueva.endsWith("/") ? nueva.substring(0, nueva.length() - 1) : nueva;
          String rutaDocum = this.TextoCarpetaDocumentum.getText() + ((nueva.equals("/")) || (nueva.equals("")) ? "" : new StringBuilder().append("/").append(nueva).toString());
          
          this.barradocum.setLabelMensa("Creando documento " + nombre + " ... ");
          this.textoLog.setText("Creando documento " + nombre + " ... ");
          String id = this.utilidadesdocumentum.importarADocumentum(nombre, listFile[i].getPath(), rutaDocum, this.tipodocumental);
          this.textoLog.setText("Creado documento " + nombre + " - ID: " + id);
          this.barradocum.setLabelMensa("Creado documento " + nombre + " - ID: " + id);
          this.panelEstado.repaint();
        }
        if (this.barradocum.getPARAR())
        {
          this.barradocum.setPARAR(false);
          return;
        }
      }
    }
  }
}
