package es.documentum.pantalla;

import com.documentum.fc.client.IDfClient;
import com.documentum.fc.client.IDfDocbaseMap;
import com.documentum.fc.client.IDfSession;
import com.documentum.fc.common.DfException;
import com.documentum.fc.impl.util.RegistryPasswordUtils;
import es.documentum.utilidades.MiProperties;
import es.documentum.utilidades.Utilidades;
import static es.documentum.utilidades.Utilidades.escribeLog;
import es.documentum.utilidades.UtilidadesDocumentum;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JList;

/**
 *
 * @author julian
 */
public class PantallaConexion extends javax.swing.JDialog {

    public static String valor = "";
    public static String docbroker = "";
    public static String repositorio = "";
    public static String versiondocumentum = "";
    public static String idrepositorio = "";
    public static String puerto = "";
    public static String usuario = "";
    public static String clave = "";

    public IDfSession idsesion;

    public IDfSession getIdsesion() {
        return idsesion;
    }

    public void setIdsesion(IDfSession idsesion) {
        this.idsesion = idsesion;
    }

    private final Utilidades util = new Utilidades();
    public static PantallaDocumentum ventanapadre = null;
    Color colornoconex = new Color(255, 200, 200);
    Color colorconex = new Color(200, 255, 200);
    public Boolean conexionOK = false;
    String boton = "";
    String dirbase = util.usuarioHome() + util.separador() + "documentumdfcs";
    String dirdfc = dirbase + util.separador() + "documentum" + util.separador() + "shared" + util.separador();

    public static String getValor() {
        return valor;
    }

    public static String getDocbroker() {
        return docbroker;
    }

    public static String getRepositorio() {
        return repositorio;
    }

    public static String getVersiondocumentum() {
        return versiondocumentum;
    }

    public static String getPuerto() {
        return puerto;
    }

    public static String getUsuario() {
        return usuario;
    }

    public static void setValor(String valor) {
        PantallaConexion.valor = valor;
    }

    public static String getIdrepositorio() {
        return idrepositorio;
    }

    public static void setIdrepositorio(String idrepositorio) {
        PantallaConexion.idrepositorio = idrepositorio;
    }

    public void setClave(String clave) {
        clave = new String(textoPassword.getPassword());
    }

    public static String getClave() {
        return clave;
    }

    public PantallaConexion(PantallaDocumentum parent, boolean modal) {
        super(parent, modal);
        ventanapadre = parent;
        dirdfc = ventanapadre.dirdfc;
        initComponents();
        try {
            setIconImage(new ImageIcon(getLogo()).getImage());
        } catch (NullPointerException e) {
            Utilidades.escribeLog("\nError cargando el Logo " + e.getMessage() + "\n");
        }
        setTitle("Conexiones Documentum");
        cargarLista();
        setLocationRelativeTo(ventanapadre);
        setVisible(true);
    }

    protected static Image getLogo() {
        //   java.net.URL imgURL = PantallaDocumentum.class.getClassLoader().getResource("es/documentum/imagenes/documentum_logo_mini.gif");
        java.net.URL imgURL = PantallaConexion.class.getClassLoader().getResource("es/documentum/imagenes/conexion.png");

        if (imgURL != null) {
            return new ImageIcon(imgURL).getImage();
        } else {
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupmenu = new javax.swing.JPopupMenu();
        opcionBorrar = new javax.swing.JMenuItem();
        panelSeleccion = new javax.swing.JScrollPane();
        listaSeleccion = new javax.swing.JList();
        botonGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textoDocbroker = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textoPuerto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textoRepositorio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textoUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textoPassword = new javax.swing.JPasswordField();
        botonSalir = new javax.swing.JButton();
        botonSelecionar = new javax.swing.JButton();
        botonTestConex = new javax.swing.JButton();
        etiquetaPanel = new javax.swing.JLabel();
        comboRepositorio = new javax.swing.JComboBox<>();
        botonConectar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        opcionBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/documentum/imagenes/borrar_peq.png"))); // NOI18N
        opcionBorrar.setText("Borrar conexión");
        opcionBorrar.setToolTipText("Borra la conexión seleccionada");
        opcionBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionBorrarActionPerformed(evt);
            }
        });
        popupmenu.add(opcionBorrar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        listaSeleccion.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaSeleccion.setName("listaSeleccion"); // NOI18N
        listaSeleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaSeleccionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listaSeleccionMousePressed(evt);
            }
        });
        panelSeleccion.setViewportView(listaSeleccion);
        listaSeleccion.getAccessibleContext().setAccessibleName("ListaSeleccion");

        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/documentum/imagenes/guardar.png"))); // NOI18N
        botonGuardar.setMnemonic('A');
        botonGuardar.setText("Guardar");
        botonGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonGuardar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botonGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        jLabel1.setText("Docbroker");
        jLabel1.setMaximumSize(new java.awt.Dimension(41, 22));
        jLabel1.setMinimumSize(new java.awt.Dimension(41, 22));
        jLabel1.setPreferredSize(new java.awt.Dimension(41, 22));

        textoDocbroker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDocbrokerActionPerformed(evt);
            }
        });

        jLabel2.setText("Puerto");

        textoPuerto.setText("1489");

        jLabel3.setText("Repositorio");

        jLabel4.setText("Usuario");

        jLabel5.setText("Password");
        jLabel5.setMaximumSize(new java.awt.Dimension(46, 21));
        jLabel5.setMinimumSize(new java.awt.Dimension(46, 21));
        jLabel5.setPreferredSize(new java.awt.Dimension(46, 21));

        textoPassword.setPreferredSize(new java.awt.Dimension(111, 22));

        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/documentum/imagenes/salir_peq.png"))); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSalir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botonSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/documentum/imagenes/seleccionar.png"))); // NOI18N
        botonSelecionar.setText("Seleccionar");
        botonSelecionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSelecionar.setMaximumSize(new java.awt.Dimension(101, 43));
        botonSelecionar.setMinimumSize(new java.awt.Dimension(101, 43));
        botonSelecionar.setPreferredSize(new java.awt.Dimension(101, 43));
        botonSelecionar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botonSelecionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSelecionarActionPerformed(evt);
            }
        });

        botonTestConex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/documentum/imagenes/conexion_peq.png"))); // NOI18N
        botonTestConex.setMnemonic('A');
        botonTestConex.setText("Test Conexión");
        botonTestConex.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonTestConex.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botonTestConex.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonTestConex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTestConexActionPerformed(evt);
            }
        });

        etiquetaPanel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiquetaPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        etiquetaPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiquetaPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiquetaPanelMouseEntered(evt);
            }
        });

        comboRepositorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRepositorioActionPerformed(evt);
            }
        });

        botonConectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/documentum/imagenes/ejecutar.png"))); // NOI18N
        botonConectar.setText("Conectar");
        botonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConectarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("1");
        jLabel6.setMaximumSize(new java.awt.Dimension(22, 22));
        jLabel6.setMinimumSize(new java.awt.Dimension(22, 22));
        jLabel6.setPreferredSize(new java.awt.Dimension(22, 22));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("2");
        jLabel7.setMaximumSize(new java.awt.Dimension(22, 22));
        jLabel7.setMinimumSize(new java.awt.Dimension(22, 22));
        jLabel7.setPreferredSize(new java.awt.Dimension(22, 22));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("6");
        jLabel8.setMaximumSize(new java.awt.Dimension(22, 22));
        jLabel8.setMinimumSize(new java.awt.Dimension(22, 22));
        jLabel8.setPreferredSize(new java.awt.Dimension(22, 22));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 153));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("5");
        jLabel9.setMaximumSize(new java.awt.Dimension(22, 22));
        jLabel9.setMinimumSize(new java.awt.Dimension(22, 22));
        jLabel9.setPreferredSize(new java.awt.Dimension(22, 22));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 153));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("4");
        jLabel10.setMaximumSize(new java.awt.Dimension(22, 22));
        jLabel10.setMinimumSize(new java.awt.Dimension(22, 22));
        jLabel10.setPreferredSize(new java.awt.Dimension(22, 22));

        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("Seleccionar la conexión (si se guardó previamente)");

        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("Rellenar datos de conexión");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 153));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("3");
        jLabel13.setMaximumSize(new java.awt.Dimension(22, 22));
        jLabel13.setMinimumSize(new java.awt.Dimension(22, 22));
        jLabel13.setPreferredSize(new java.awt.Dimension(22, 22));

        jLabel14.setForeground(new java.awt.Color(0, 0, 153));
        jLabel14.setText("Recuperar la lista de repositorios");

        jLabel15.setForeground(new java.awt.Color(0, 0, 153));
        jLabel15.setText("Probar la conexión");

        jLabel16.setForeground(new java.awt.Color(0, 0, 153));
        jLabel16.setText("Usar la conexión");

        jLabel17.setForeground(new java.awt.Color(0, 0, 153));
        jLabel17.setText("Guarda la conexión");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiquetaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(398, 398, 398))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelSeleccion)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textoDocbroker, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textoPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(comboRepositorio, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textoRepositorio, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(34, 34, 34)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(botonConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(65, 65, 65))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(botonSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(406, 406, 406))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(botonTestConex, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonGuardar, botonSalir, botonSelecionar, botonTestConex});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(4, 4, 4)
                        .addComponent(textoDocbroker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(botonConectar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboRepositorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoRepositorio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonGuardar)
                    .addComponent(botonSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSalir)
                    .addComponent(botonTestConex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiquetaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {textoDocbroker, textoPuerto, textoRepositorio});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botonGuardar, botonSalir, botonSelecionar, botonTestConex});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel5, textoPassword, textoUsuario});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        String directorio = dirdfc + "repos" + util.separador() + textoDocbroker.getText() + util.separador();
        util.crearDirectorio(directorio);
        util.copiarFichero(dirdfc + "dfc.properties", directorio + "dfc.properties");
        MiProperties prop = util.leerPropeties(dirdfc + "dfc.properties");
        prop.setProperty("dfc.docbroker.host[0]", textoDocbroker.getText());
        prop.setProperty("dfc.docbroker.port[0]", textoPuerto.getText());
        prop.remove("usuario");
        prop.remove("repositorio");
        prop.remove("password");
        MiProperties propapp = util.leerPropeties(dirdfc + "DocumentumDFCs.properties");
        propapp.setProperty("usuario", textoUsuario.getText());
        try {
            propapp.setProperty("password", RegistryPasswordUtils.encrypt(new String(textoPassword.getPassword())));
        } catch (DfException ex) {
            escribeLog("Error al guardar datos del repositorio. Error: " + ex.getMessage());
        }
        propapp.setProperty("repositorio", textoRepositorio.getText());
        util.escribirProperties(directorio + "dfc.properties", prop);
        util.escribirProperties(directorio + "DocumentumDFCs.properties", propapp);
        int numelem = listaSeleccion.getModel().getSize();
        int pos = 0;

        while (pos < numelem) {
            if (listaSeleccion.getModel().getElementAt(pos).equals(textoDocbroker.getText().toLowerCase())) {
                break;
            }
            pos++;
        }
        if (pos >= numelem) {
            DefaultListModel ModeloLista = (DefaultListModel) listaSeleccion.getModel();
            ModeloLista.addElement(textoDocbroker.getText().toLowerCase());
            listaSeleccion.setModel(ModeloLista);
            listaSeleccion.setSelectedIndex(pos);
        }

    }//GEN-LAST:event_botonGuardarActionPerformed

    private void textoDocbrokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDocbrokerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDocbrokerActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        valor = "SALIR";
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSelecionarActionPerformed
        if (conexionOK) {
            seleccionarConexion();
            this.dispose();
        } else {
            etiquetaPanel.setText("Debe confirma que la conexión es correcta. Use el botón \"Test Conexión\"");
            botonTestConex.requestFocus();
        }
    }//GEN-LAST:event_botonSelecionarActionPerformed

    private void listaSeleccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaSeleccionMouseClicked
        if (listaSeleccion.getModel().getSize() > 0) {
            if (listaSeleccion.getSelectedIndex() >= 0) {
                String directoriodfc = listaSeleccion.getModel().getElementAt(listaSeleccion.getSelectedIndex()).toString();
                String directorio = dirdfc + "repos" + util.separador() + directoriodfc + util.separador();
                MiProperties prop = util.leerPropeties(directorio + "dfc.properties");
                textoDocbroker.setText(prop.getProperty("dfc.docbroker.host[0]"));
                textoPuerto.setText(prop.getProperty("dfc.docbroker.port[0]"));
                MiProperties propapp = util.leerPropeties(directorio + "DocumentumDFCs.properties");
                if (propapp == null) {
                    propapp = new MiProperties();
                    propapp.setProperty("repositorio", directoriodfc);
                    propapp.setProperty("usuario", "");
                    propapp.setProperty("password", "");
                    util.escribirProperties(directorio + "DocumentumDFCs.properties", propapp);
                }
                textoRepositorio.setText(propapp.getProperty("repositorio"));
                textoUsuario.setText(propapp.getProperty("usuario"));
                try {
                    textoPassword.setText(RegistryPasswordUtils.decrypt(propapp.getProperty("password")));
                } catch (DfException ex) {
                    escribeLog("Error al hacer click en la lista. Error: " + ex.getMessage());
                }

                textoDocbroker.requestFocus();
                this.repaint();
            }
        }
    }//GEN-LAST:event_listaSeleccionMouseClicked

    private void botonTestConexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTestConexActionPerformed
        if (comprobarValores()) {
            botonTestConex.setEnabled(false);
            etiquetaPanel.setText("Estableciendo Conexión con Documentum ...");
            MiProperties prop = util.leerPropeties(dirdfc + "dfc.properties");
            prop.setProperty("dfc.docbroker.host[0]", textoDocbroker.getText());
            prop.setProperty("dfc.docbroker.port[0]", textoPuerto.getText());
            MiProperties appprop = util.leerPropeties(dirdfc + "DocumentumDFCs.properties");
            appprop.setProperty("usuario", textoUsuario.getText());
            try {
                appprop.setProperty("password", RegistryPasswordUtils.encrypt(new String(textoPassword.getPassword())));
            } catch (Exception ex) {
            }
            appprop.setProperty("repositorio", textoRepositorio.getText());
            util.escribirProperties(dirdfc + "dfc.properties", prop);
            util.escribirProperties(dirdfc + "DocumentumDFCs.properties", appprop);
            UtilidadesDocumentum utildocum = new UtilidadesDocumentum(dirdfc + "dfc.properties");
            utildocum.setPro(prop);
            try {
                Thread.sleep(500);
            } catch (InterruptedException ex) {
                botonTestConex.setEnabled(true);
            }

            idsesion = utildocum.conectarDocumentum(textoUsuario.getText(), new String(textoPassword.getPassword()),
                    textoRepositorio.getText(), textoDocbroker.getText(), textoPuerto.getText());

            if (idsesion == null) {
                botonTestConex.setBackground(colornoconex);
                conexionOK = false;
                etiquetaPanel.setText(utildocum.dameError());
            } else {
                botonTestConex.setBackground(colorconex);
                conexionOK = true;
                etiquetaPanel.setText("Conexión correcta con Documentum");
                versiondocumentum = utildocum.dameVersionDocumentum();
                idrepositorio = utildocum.dameIdRepositorio();
                docbroker = textoDocbroker.getText();
                repositorio = textoRepositorio.getText();
                puerto = textoPuerto.getText();
                usuario = textoUsuario.getText();
                try {
                    IDfDocbaseMap dfDocbaseMap = idsesion.getClient().getDocbaseMap();
                    System.out.println("Repositorios disponibles (" + docbroker + " - " + puerto + "): ");
                    for (int i = 0; i < dfDocbaseMap.getDocbaseCount(); i++) {
                        String docbaseName = dfDocbaseMap.getDocbaseName(i);
                        String docbaseDescription = dfDocbaseMap.getDocbaseDescription(i);
                        String docbaseid = dfDocbaseMap.getDocbaseId(i);
                        System.out.println(docbaseName + "\t " + docbaseid + "(" + Integer.toHexString(Integer.parseInt(docbaseid)) + ")\t->\t" + docbaseDescription);
                    }
                } catch (DfException | NumberFormatException ex) {

                }

            }
            botonTestConex.setEnabled(true);
        }
    }//GEN-LAST:event_botonTestConexActionPerformed

    private void etiquetaPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaPanelMouseEntered
        etiquetaPanel.setToolTipText(etiquetaPanel.getText());
    }//GEN-LAST:event_etiquetaPanelMouseEntered

    private void listaSeleccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaSeleccionMousePressed
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON3 && listaSeleccion.getModel().getSize() > 0) {
            popupmenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_listaSeleccionMousePressed

    private void opcionBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionBorrarActionPerformed
        if (!listaSeleccion.isSelectionEmpty()) {
            String directorio = listaSeleccion.getModel().getElementAt(listaSeleccion.getSelectedIndex()).toString();
            System.out.println(dirdfc + "repos" + util.separador() + directorio);
            util.borrarDirectorio(dirdfc + "repos" + util.separador() + directorio);
            listaSeleccion.removeAll();
            cargarLista();
        }
    }//GEN-LAST:event_opcionBorrarActionPerformed

    private void etiquetaPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaPanelMouseClicked
        if (evt.getClickCount() == 2 && evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
            Utilidades.copiarTextoPortapapeles(etiquetaPanel.getText());
        }
    }//GEN-LAST:event_etiquetaPanelMouseClicked

    private void comboRepositorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRepositorioActionPerformed

        textoRepositorio.setText(comboRepositorio.getItemAt(comboRepositorio.getSelectedIndex()));

    }//GEN-LAST:event_comboRepositorioActionPerformed

    private void botonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConectarActionPerformed
        boton = "conectar";
        IDfClient dfClient = conectar_bocbroker();
        if (dfClient != null) {
            cargarRepositorios(dfClient);
        }
    }//GEN-LAST:event_botonConectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                PantallaConexion dialog = new PantallaConexion(ventanapadre, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setLocationRelativeTo(ventanapadre);
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConectar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonSelecionar;
    private javax.swing.JButton botonTestConex;
    private javax.swing.JComboBox<String> comboRepositorio;
    private javax.swing.JLabel etiquetaPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList listaSeleccion;
    private javax.swing.JMenuItem opcionBorrar;
    private javax.swing.JScrollPane panelSeleccion;
    private javax.swing.JPopupMenu popupmenu;
    private javax.swing.JTextField textoDocbroker;
    private javax.swing.JPasswordField textoPassword;
    private javax.swing.JTextField textoPuerto;
    private javax.swing.JTextField textoRepositorio;
    private javax.swing.JTextField textoUsuario;
    // End of variables declaration//GEN-END:variables

    public void asignariconos() {
    }

    private void cargarLista() {
        File dirrepos = new File(dirdfc + "repos" + util.separador());
        String[] listadir = dirrepos.list();
        DefaultListModel ModeloLista = new DefaultListModel();
        if (listadir == null) {
            listaSeleccion.setModel(ModeloLista);
            return;
        }

        if (listadir.length > 0) {
            for (int i = 0; i < listadir.length; i++) {
                ModeloLista.add(i, listadir[i]);
            }

        }
        listaSeleccion.setModel(ModeloLista);
        listaSeleccion.setCellRenderer(new MiCellRenderer());
    }

    class MiCellRenderer extends DefaultListCellRenderer {

        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            setOpaque(true);
            boolean oddRow = (index % 2 == 0);
            if (oddRow) {
                setBackground(Color.WHITE);
            } else {
                setBackground(new Color(245, 245, 245)); // gris claro
            }

            if (isSelected) {
                setBackground(new Color(175, 205, 235)); // azul claro selección
            }

            return this;
        }
    }

    private void seleccionarConexion() {
        String directorio = dirdfc;
        if (listaSeleccion.getModel().getSize() > 0) {
            if (listaSeleccion.getSelectedIndex() > 0) {
                directorio = directorio + "repos" + util.separador() + listaSeleccion.getModel().getElementAt(listaSeleccion.getSelectedIndex()) + util.separador();
            }
        }
        MiProperties prop = util.leerPropeties(directorio + "dfc.properties");
        prop.setProperty("dfc.docbroker.host[0]", textoDocbroker.getText());
        prop.setProperty("dfc.docbroker.port[0]", textoPuerto.getText());
        prop.remove("usuario");
        prop.remove("repositorio");
        prop.remove("password");
        MiProperties propapp = util.leerPropeties(directorio + "DocumentumDFCs.properties");
        propapp.setProperty("repositorio", textoRepositorio.getText());
        propapp.setProperty("usuario", textoUsuario.getText());
        try {
            propapp.setProperty("password", RegistryPasswordUtils.encrypt(new String(textoPassword.getPassword())));
        } catch (Exception ex) {
        }
        util.escribirProperties(dirdfc + "dfc.properties", prop);
        util.escribirProperties(dirdfc + "DocumentumDFCs.properties", propapp);
        valor = "SELECION";
        clave = new String(textoPassword.getPassword());
        docbroker = textoDocbroker.getText();
        repositorio = textoRepositorio.getText();

    }

    private Boolean comprobarValores() {
        Boolean resultado = true;
        if (textoDocbroker.getText().isEmpty()) {
            etiquetaPanel.setText("Debe dar un valor al Docbroker");
            textoDocbroker.requestFocus();
            return false;
        }
        if (textoPuerto.getText().isEmpty()) {
            etiquetaPanel.setText("Debe dar un valor al Puerto");
            textoPuerto.requestFocus();
            return false;
        }

        if (textoUsuario.getText().isEmpty()) {
            etiquetaPanel.setText("Debe indicar el Usuario");
            textoUsuario.requestFocus();
            return false;
        }
        if (new String(textoPassword.getPassword()).isEmpty()) {
            etiquetaPanel.setText("Debe indicar la Password del Usuario");
            textoPassword.requestFocus();
            return false;
        }

        if (boton.equals("conectar")) {
            boton = "";
        } else if (textoRepositorio.getText().isEmpty()) {
            etiquetaPanel.setText("Debe dar un valor al Repositorio");
            textoRepositorio.requestFocus();
            return false;
        }
        etiquetaPanel.setText("");
        return resultado;
    }

    private IDfClient conectar_bocbroker() {
        comboRepositorio.removeAllItems();
        if (comprobarValores()) {
            MiProperties prop = util.leerPropeties(dirdfc + "dfc.properties");
            prop.setProperty("dfc.docbroker.host[0]", textoDocbroker.getText());
            prop.setProperty("dfc.docbroker.port[0]", textoPuerto.getText());
            MiProperties propapp = util.leerPropeties(dirdfc + "DocumentumDFCs.properties");
            if (propapp == null) {
                propapp = new MiProperties();
            }

            propapp.setProperty("usuario", textoUsuario.getText());
            try {
                propapp.setProperty("password", RegistryPasswordUtils.encrypt(new String(textoPassword.getPassword())));
            } catch (Exception ex) {
            }
            propapp.setProperty("repositorio", textoRepositorio.getText());
            util.escribirProperties(dirdfc + "dfc.properties", prop);
            util.escribirProperties(dirdfc + "DocumentumDFCs.properties", propapp);
            UtilidadesDocumentum utildocum = new UtilidadesDocumentum(dirdfc + "dfc.properties");
            try {
                Thread.sleep(500);
            } catch (InterruptedException ex) {
                escribeLog("Error al ejecutar (conectar_bocbroker)" + ex.getMessage());
            }
            return utildocum.dameCliente();
        }
        return null;
    }

    private void cargarRepositorios(IDfClient dfClient) {
        try {
            if (dfClient == null) {
                comboRepositorio.removeAllItems();
                return;
            }

            IDfDocbaseMap dfDocbaseMap = dfClient.getDocbaseMap();
            DefaultComboBoxModel ModeloLista = new DefaultComboBoxModel();
            comboRepositorio.removeAllItems();
            comboRepositorio.setModel(ModeloLista);
            for (int i = 0; i < dfDocbaseMap.getDocbaseCount(); i++) {
                String docbaseName = dfDocbaseMap.getDocbaseName(i);
                String docbaseDescription = dfDocbaseMap.getDocbaseDescription(i);
                ModeloLista.addElement(dfDocbaseMap.getDocbaseName(i));
                System.out.println(docbaseName + " | " + docbaseDescription);
            }
            comboRepositorio.setModel(ModeloLista);
            comboRepositorio.doLayout();
            if (textoRepositorio.getText().isEmpty()) {
                textoRepositorio.setText(comboRepositorio.getItemAt(comboRepositorio.getSelectedIndex()));
            }
        } catch (DfException ex) {
            escribeLog("Error al ejecutar (cargarRepositorios)" + ex.getMessage());
        }
    }
}
