package es.documentum.pantalla;

import com.documentum.fc.client.IDfCollection;
import com.documentum.fc.client.IDfSession;
import com.documentum.fc.client.IDfTypedObject;
import com.documentum.fc.common.DfException;
import es.documentum.Beans.AtributosDocumentum;
import es.documentum.utilidades.Utilidades;
import es.documentum.utilidades.UtilidadesDocumentum;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author julian.collado
 */
public class PantallaPropiedades extends javax.swing.JDialog {

    public String r_object_id = "";
    PantallaDocumentum pdocum = null;
    Utilidades util = null;
    UtilidadesDocumentum docum = null;
    String componente = "";

    public String getR_object_id() {
        return r_object_id;
    }

    public void setR_object_id(String r_object_id) {
        this.r_object_id = r_object_id;
    }

    public PantallaPropiedades(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        pdocum = (PantallaDocumentum) parent;
        setLocationRelativeTo(parent);
        initComponents();
        try {
            setIconImage(new ImageIcon(getLogo()).getImage());
        } catch (NullPointerException e) {
            Utilidades.escribeLog("\nError cargando el Logo " + e.getMessage() + "\n");
        }
        asignarIcono();
        util = pdocum.util;
        docum = pdocum.utilDocum;
        //      consultarValores(r_object_id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupEditar = new javax.swing.JPopupMenu();
        opcionCopiar = new javax.swing.JMenuItem();
        botonCerrar = new javax.swing.JButton();
        CajaPropiedades = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        labelCheckout = new javax.swing.JTextField();
        labelI_partition = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelA_content_type = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        labelName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelR_modify_date = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelR_creation_date = new javax.swing.JTextField();
        labelOwner_name = new javax.swing.JTextField();
        labelR_object_id = new javax.swing.JTextField();
        labelAcl_name = new javax.swing.JTextField();
        labelR_full_content_size = new javax.swing.JTextField();
        labelAuthors = new javax.swing.JTextField();
        labelPathSistema = new javax.swing.JTextField();
        labelR_object_type = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelPathDocumentum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelA_storage_type = new javax.swing.JTextField();

        opcionCopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/documentum/imagenes/copiar.png"))); // NOI18N
        opcionCopiar.setText("Copiar Ctrl+C");
        opcionCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionCopiarActionPerformed(evt);
            }
        });
        popupEditar.add(opcionCopiar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Propiedades");
        setMaximumSize(new java.awt.Dimension(961, 576));
        setResizable(false);

        botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/documentum/imagenes/salir_peq.png"))); // NOI18N
        botonCerrar.setText("Cerrar");
        botonCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botonCerrar.setMaximumSize(new java.awt.Dimension(89, 28));
        botonCerrar.setMinimumSize(new java.awt.Dimension(89, 28));
        botonCerrar.setPreferredSize(new java.awt.Dimension(89, 28));
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        CajaPropiedades.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("owner_name: ");

        labelCheckout.setEditable(false);
        labelCheckout.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelCheckout.setForeground(new java.awt.Color(0, 51, 153));
        labelCheckout.setBorder(null);
        labelCheckout.setCaretColor(new java.awt.Color(0, 51, 153));
        labelCheckout.setMinimumSize(new java.awt.Dimension(6, 24));
        labelCheckout.setPreferredSize(new java.awt.Dimension(505, 24));

        labelI_partition.setEditable(false);
        labelI_partition.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelI_partition.setForeground(new java.awt.Color(0, 51, 153));
        labelI_partition.setBorder(null);
        labelI_partition.setCaretColor(new java.awt.Color(0, 51, 153));
        labelI_partition.setMinimumSize(new java.awt.Dimension(6, 24));
        labelI_partition.setPreferredSize(new java.awt.Dimension(505, 24));
        labelI_partition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelI_partitionMousePressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setText("check in: ");
        jLabel13.setMaximumSize(new java.awt.Dimension(68, 24));
        jLabel13.setMinimumSize(new java.awt.Dimension(68, 24));
        jLabel13.setPreferredSize(new java.awt.Dimension(68, 24));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setText("acl_name: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("r_creation_date:");

        labelA_content_type.setEditable(false);
        labelA_content_type.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelA_content_type.setForeground(new java.awt.Color(0, 51, 153));
        labelA_content_type.setBorder(null);
        labelA_content_type.setCaretColor(new java.awt.Color(0, 51, 153));
        labelA_content_type.setMinimumSize(new java.awt.Dimension(6, 24));
        labelA_content_type.setPreferredSize(new java.awt.Dimension(505, 24));
        labelA_content_type.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelA_content_typeMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("a_storage_type:");

        labelName.setEditable(false);
        labelName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelName.setForeground(new java.awt.Color(0, 51, 153));
        labelName.setBorder(null);
        labelName.setCaretColor(new java.awt.Color(0, 51, 153));
        labelName.setMinimumSize(new java.awt.Dimension(6, 24));
        labelName.setPreferredSize(new java.awt.Dimension(505, 24));
        labelName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelNameMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("r_modify_date:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setText("authors[0]:");
        jLabel15.setMaximumSize(new java.awt.Dimension(76, 24));
        jLabel15.setMinimumSize(new java.awt.Dimension(76, 24));
        jLabel15.setPreferredSize(new java.awt.Dimension(76, 24));

        labelR_modify_date.setEditable(false);
        labelR_modify_date.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelR_modify_date.setForeground(new java.awt.Color(0, 51, 153));
        labelR_modify_date.setBorder(null);
        labelR_modify_date.setCaretColor(new java.awt.Color(0, 51, 153));
        labelR_modify_date.setMinimumSize(new java.awt.Dimension(6, 24));
        labelR_modify_date.setPreferredSize(new java.awt.Dimension(505, 24));
        labelR_modify_date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelR_modify_dateMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("path Sistema:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("path Documentum:");

        labelR_creation_date.setEditable(false);
        labelR_creation_date.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelR_creation_date.setForeground(new java.awt.Color(0, 51, 153));
        labelR_creation_date.setBorder(null);
        labelR_creation_date.setCaretColor(new java.awt.Color(0, 51, 153));
        labelR_creation_date.setMinimumSize(new java.awt.Dimension(6, 24));
        labelR_creation_date.setPreferredSize(new java.awt.Dimension(505, 24));
        labelR_creation_date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelR_creation_dateMousePressed(evt);
            }
        });

        labelOwner_name.setEditable(false);
        labelOwner_name.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelOwner_name.setForeground(new java.awt.Color(0, 51, 153));
        labelOwner_name.setBorder(null);
        labelOwner_name.setCaretColor(new java.awt.Color(0, 51, 153));
        labelOwner_name.setMinimumSize(new java.awt.Dimension(6, 24));
        labelOwner_name.setPreferredSize(new java.awt.Dimension(505, 24));
        labelOwner_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelOwner_nameMousePressed(evt);
            }
        });

        labelR_object_id.setEditable(false);
        labelR_object_id.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelR_object_id.setForeground(new java.awt.Color(0, 51, 153));
        labelR_object_id.setBorder(null);
        labelR_object_id.setCaretColor(new java.awt.Color(0, 51, 153));
        labelR_object_id.setMinimumSize(new java.awt.Dimension(6, 24));
        labelR_object_id.setPreferredSize(new java.awt.Dimension(505, 24));
        labelR_object_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelR_object_idMousePressed(evt);
            }
        });

        labelAcl_name.setEditable(false);
        labelAcl_name.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelAcl_name.setForeground(new java.awt.Color(0, 51, 153));
        labelAcl_name.setBorder(null);
        labelAcl_name.setCaretColor(new java.awt.Color(0, 51, 153));
        labelAcl_name.setMinimumSize(new java.awt.Dimension(6, 24));
        labelAcl_name.setPreferredSize(new java.awt.Dimension(505, 24));
        labelAcl_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelAcl_nameMousePressed(evt);
            }
        });

        labelR_full_content_size.setEditable(false);
        labelR_full_content_size.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelR_full_content_size.setForeground(new java.awt.Color(0, 51, 153));
        labelR_full_content_size.setBorder(null);
        labelR_full_content_size.setCaretColor(new java.awt.Color(0, 51, 153));
        labelR_full_content_size.setMinimumSize(new java.awt.Dimension(6, 24));
        labelR_full_content_size.setPreferredSize(new java.awt.Dimension(505, 24));
        labelR_full_content_size.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelR_full_content_sizeMousePressed(evt);
            }
        });

        labelAuthors.setEditable(false);
        labelAuthors.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelAuthors.setForeground(new java.awt.Color(0, 51, 153));
        labelAuthors.setBorder(null);
        labelAuthors.setCaretColor(new java.awt.Color(0, 51, 153));
        labelAuthors.setMinimumSize(new java.awt.Dimension(6, 24));
        labelAuthors.setPreferredSize(new java.awt.Dimension(505, 24));
        labelAuthors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelAuthorsMousePressed(evt);
            }
        });

        labelPathSistema.setEditable(false);
        labelPathSistema.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelPathSistema.setForeground(new java.awt.Color(0, 51, 153));
        labelPathSistema.setBorder(null);
        labelPathSistema.setCaretColor(new java.awt.Color(0, 51, 153));
        labelPathSistema.setMinimumSize(new java.awt.Dimension(6, 24));
        labelPathSistema.setPreferredSize(new java.awt.Dimension(505, 24));
        labelPathSistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelPathSistemaMousePressed(evt);
            }
        });

        labelR_object_type.setEditable(false);
        labelR_object_type.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelR_object_type.setForeground(new java.awt.Color(0, 51, 153));
        labelR_object_type.setBorder(null);
        labelR_object_type.setCaretColor(new java.awt.Color(0, 51, 153));
        labelR_object_type.setMinimumSize(new java.awt.Dimension(6, 24));
        labelR_object_type.setPreferredSize(new java.awt.Dimension(505, 24));
        labelR_object_type.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelR_object_typeMousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setText("i_partition: ");
        jLabel12.setMaximumSize(new java.awt.Dimension(76, 24));
        jLabel12.setMinimumSize(new java.awt.Dimension(76, 24));
        jLabel12.setPreferredSize(new java.awt.Dimension(76, 24));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("r_full_content_size: ");
        jLabel9.setMaximumSize(new java.awt.Dimension(134, 24));
        jLabel9.setMinimumSize(new java.awt.Dimension(134, 24));
        jLabel9.setPreferredSize(new java.awt.Dimension(134, 24));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("r_object_id:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("name:");

        labelPathDocumentum.setEditable(false);
        labelPathDocumentum.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelPathDocumentum.setForeground(new java.awt.Color(0, 51, 153));
        labelPathDocumentum.setBorder(null);
        labelPathDocumentum.setCaretColor(new java.awt.Color(0, 51, 153));
        labelPathDocumentum.setMinimumSize(new java.awt.Dimension(6, 24));
        labelPathDocumentum.setPreferredSize(new java.awt.Dimension(505, 24));
        labelPathDocumentum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelPathDocumentumMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("r_object_type:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("a_content_type:");

        labelA_storage_type.setEditable(false);
        labelA_storage_type.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelA_storage_type.setForeground(new java.awt.Color(0, 51, 153));
        labelA_storage_type.setBorder(null);
        labelA_storage_type.setCaretColor(new java.awt.Color(0, 51, 153));
        labelA_storage_type.setMinimumSize(new java.awt.Dimension(6, 24));
        labelA_storage_type.setPreferredSize(new java.awt.Dimension(505, 24));
        labelA_storage_type.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelA_storage_typeMousePressed(evt);
            }
        });

        javax.swing.GroupLayout CajaPropiedadesLayout = new javax.swing.GroupLayout(CajaPropiedades);
        CajaPropiedades.setLayout(CajaPropiedadesLayout);
        CajaPropiedadesLayout.setHorizontalGroup(
            CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CajaPropiedadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CajaPropiedadesLayout.createSequentialGroup()
                        .addGroup(CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelR_object_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CajaPropiedadesLayout.createSequentialGroup()
                        .addGroup(CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPathSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CajaPropiedadesLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(labelAuthors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CajaPropiedadesLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelI_partition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CajaPropiedadesLayout.createSequentialGroup()
                        .addGroup(CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelR_full_content_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelA_storage_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CajaPropiedadesLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(labelA_content_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CajaPropiedadesLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelPathDocumentum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CajaPropiedadesLayout.createSequentialGroup()
                        .addGroup(CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelR_object_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelR_creation_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelR_modify_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CajaPropiedadesLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelOwner_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CajaPropiedadesLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(labelAcl_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CajaPropiedadesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel15, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        CajaPropiedadesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelA_content_type, labelA_storage_type, labelAcl_name, labelAuthors, labelCheckout, labelI_partition, labelName, labelOwner_name, labelPathDocumentum, labelPathSistema, labelR_creation_date, labelR_full_content_size, labelR_modify_date, labelR_object_id, labelR_object_type});

        CajaPropiedadesLayout.setVerticalGroup(
            CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CajaPropiedadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelR_object_id, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelR_object_type, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelR_creation_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(labelR_modify_date, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelOwner_name, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelAcl_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelPathDocumentum, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelPathSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(labelA_content_type, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelR_full_content_size, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelA_storage_type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelI_partition, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CajaPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAuthors, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        CajaPropiedadesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        CajaPropiedadesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel11, labelOwner_name});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CajaPropiedades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CajaPropiedades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void opcionCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionCopiarActionPerformed
        if (componente.equals("labelName")) {
            if (labelName.getText() == null) {
                return;
            }
            if (labelName.getSelectedText() == null || labelName.getSelectedText().isEmpty()) {
                Utilidades.copiarTextoPortapapeles(labelName.getText());
            } else {
                Utilidades.copiarTextoPortapapeles(labelName.getSelectedText());
            }
        }

        if (componente.equals("labelR_object_id")) {
            if (labelR_object_id.getText() == null) {
                return;
            }
            if (labelR_object_id.getSelectedText() == null || labelR_object_id.getSelectedText().isEmpty()) {
                Utilidades.copiarTextoPortapapeles(labelR_object_id.getText());
            } else {
                Utilidades.copiarTextoPortapapeles(labelR_object_id.getSelectedText());
            }
        }

        if (componente.equals("labelPathSistema")) {
            if (labelPathSistema.getText() == null) {
                return;
            }
            if (labelPathSistema.getSelectedText() == null || labelPathSistema.getSelectedText().isEmpty()) {
                Utilidades.copiarTextoPortapapeles(labelPathSistema.getText());
            } else {
                Utilidades.copiarTextoPortapapeles(labelPathSistema.getSelectedText());
            }
        }

        if (componente.equals("labelPathDocumentum")) {
            if (labelPathDocumentum.getText() == null) {
                return;
            }
            if (labelPathDocumentum.getSelectedText() == null || labelPathDocumentum.getSelectedText().isEmpty()) {
                Utilidades.copiarTextoPortapapeles(labelPathDocumentum.getText());
            } else {
                Utilidades.copiarTextoPortapapeles(labelPathDocumentum.getSelectedText());
            }
        }

        if (componente.equals("labelR_object_type")) {
            if (labelR_object_type.getText() == null) {
                return;
            }
            if (labelR_object_type.getSelectedText() == null || labelR_object_type.getSelectedText().isEmpty()) {
                Utilidades.copiarTextoPortapapeles(labelR_object_type.getText());
            } else {
                Utilidades.copiarTextoPortapapeles(labelR_object_type.getSelectedText());
            }
        }

        if (componente.equals("labelR_creation_date")) {
            if (labelR_creation_date.getText() == null) {
                return;
            }
            if (labelR_creation_date.getSelectedText() == null || labelR_creation_date.getSelectedText().isEmpty()) {
                Utilidades.copiarTextoPortapapeles(labelR_creation_date.getText());
            } else {
                Utilidades.copiarTextoPortapapeles(labelR_creation_date.getSelectedText());
            }
        }

        if (componente.equals("labelR_modify_date")) {
            if (labelR_modify_date.getText() == null) {
                return;
            }
            if (labelR_modify_date.getSelectedText() == null || labelR_modify_date.getSelectedText().isEmpty()) {
                Utilidades.copiarTextoPortapapeles(labelR_modify_date.getText());
            } else {
                Utilidades.copiarTextoPortapapeles(labelR_modify_date.getSelectedText());
            }
        }

        if (componente.equals("labelA_content_type")) {
            if (labelA_content_type.getText() == null) {
                return;
            }
            if (labelA_content_type.getSelectedText() == null || labelA_content_type.getSelectedText().isEmpty()) {
                Utilidades.copiarTextoPortapapeles(labelA_content_type.getText());
            } else {
                Utilidades.copiarTextoPortapapeles(labelA_content_type.getSelectedText());
            }
        }

        if (componente.equals("labelR_full_content_size")) {
            if (labelR_full_content_size.getText() == null) {
                return;
            }
            if (labelR_full_content_size.getSelectedText() == null || labelR_full_content_size.getSelectedText().isEmpty()) {
                Utilidades.copiarTextoPortapapeles(labelR_full_content_size.getText());
            } else {
                Utilidades.copiarTextoPortapapeles(labelR_full_content_size.getSelectedText());
            }
        }

        if (componente.equals("labelA_storage_type")) {
            if (labelA_storage_type.getText() == null) {
                return;
            }
            if (labelA_storage_type.getSelectedText() == null || labelA_storage_type.getSelectedText().isEmpty()) {
                Utilidades.copiarTextoPortapapeles(labelA_storage_type.getText());
            } else {
                Utilidades.copiarTextoPortapapeles(labelA_storage_type.getSelectedText());
            }
        }

        if (componente.equals("labelOwner_name")) {
            if (labelOwner_name.getText() == null) {
                return;
            }
            if (labelOwner_name.getSelectedText() == null || labelOwner_name.getSelectedText().isEmpty()) {
                Utilidades.copiarTextoPortapapeles(labelOwner_name.getText());
            } else {
                Utilidades.copiarTextoPortapapeles(labelOwner_name.getSelectedText());
            }
        }

        if (componente.equals("labelAcl_name")) {
            if (labelAcl_name.getText() == null) {
                return;
            }
            if (labelAcl_name.getSelectedText() == null || labelAcl_name.getSelectedText().isEmpty()) {
                Utilidades.copiarTextoPortapapeles(labelAcl_name.getText());
            } else {
                Utilidades.copiarTextoPortapapeles(labelAcl_name.getSelectedText());
            }
        }

        if (componente.equals("labelI_partition")) {
            if (labelI_partition.getText() == null) {
                return;
            }
            if (labelI_partition.getSelectedText() == null || labelI_partition.getSelectedText().isEmpty()) {
                Utilidades.copiarTextoPortapapeles(labelI_partition.getText());
            } else {
                Utilidades.copiarTextoPortapapeles(labelI_partition.getSelectedText());
            }
        }

        if (componente.equals("labelAuthors")) {
            if (labelAuthors.getText() == null) {
                return;
            }
            if (labelAuthors.getSelectedText() == null || labelAuthors.getSelectedText().isEmpty()) {
                Utilidades.copiarTextoPortapapeles(labelAuthors.getText());
            } else {
                Utilidades.copiarTextoPortapapeles(labelAuthors.getSelectedText());
            }
        }
    }//GEN-LAST:event_opcionCopiarActionPerformed

    private void labelNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNameMousePressed
        popupmenu(evt);
        componente = "labelName";
    }//GEN-LAST:event_labelNameMousePressed

    private void labelR_object_idMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelR_object_idMousePressed
        popupmenu(evt);
        componente = "labelR_object_id";
    }//GEN-LAST:event_labelR_object_idMousePressed

    private void labelPathSistemaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPathSistemaMousePressed
        popupmenu(evt);
        componente = "labelPathSistema";
    }//GEN-LAST:event_labelPathSistemaMousePressed

    private void labelPathDocumentumMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPathDocumentumMousePressed
        popupmenu(evt);
        componente = "labelPathDocumentum";
    }//GEN-LAST:event_labelPathDocumentumMousePressed

    private void labelR_object_typeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelR_object_typeMousePressed
        popupmenu(evt);
        componente = "labelR_object_type";
    }//GEN-LAST:event_labelR_object_typeMousePressed

    private void labelR_creation_dateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelR_creation_dateMousePressed
        popupmenu(evt);
        componente = "labelR_creation_date";
    }//GEN-LAST:event_labelR_creation_dateMousePressed

    private void labelR_modify_dateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelR_modify_dateMousePressed
        popupmenu(evt);
        componente = "labelR_modify_date";
    }//GEN-LAST:event_labelR_modify_dateMousePressed

    private void labelA_content_typeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelA_content_typeMousePressed
        popupmenu(evt);
        componente = "labelA_content_type";
    }//GEN-LAST:event_labelA_content_typeMousePressed

    private void labelR_full_content_sizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelR_full_content_sizeMousePressed
        popupmenu(evt);
        componente = "labelR_full_content_size";
    }//GEN-LAST:event_labelR_full_content_sizeMousePressed

    private void labelA_storage_typeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelA_storage_typeMousePressed
        popupmenu(evt);
        componente = "labelA_storage_type";
    }//GEN-LAST:event_labelA_storage_typeMousePressed

    private void labelOwner_nameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelOwner_nameMousePressed
        popupmenu(evt);
        componente = "labelOwner_name";
    }//GEN-LAST:event_labelOwner_nameMousePressed

    private void labelAcl_nameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAcl_nameMousePressed
        popupmenu(evt);
        componente = "labelAcl_name";
    }//GEN-LAST:event_labelAcl_nameMousePressed

    private void labelI_partitionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelI_partitionMousePressed
        popupmenu(evt);
        componente = "labelI_partition";
    }//GEN-LAST:event_labelI_partitionMousePressed

    private void labelAuthorsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAuthorsMousePressed
        popupmenu(evt);
        componente = "labelAuthors";
    }//GEN-LAST:event_labelAuthorsMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Utilidades.escribeLog("Error en el main de Acercade " + " - " + ex.getMessage());
        } catch (InstantiationException ex) {
            Utilidades.escribeLog("Error en el main de Acercade " + " - " + ex.getMessage());
        } catch (IllegalAccessException ex) {
            Utilidades.escribeLog("Error en el main de Acercade " + " - " + ex.getMessage());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            Utilidades.escribeLog("Error en el main de Acercade " + " - " + ex.getMessage());
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PantallaPropiedades dialog = new PantallaPropiedades(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setLocationRelativeTo(dialog.getParent());
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CajaPropiedades;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField labelA_content_type;
    private javax.swing.JTextField labelA_storage_type;
    private javax.swing.JTextField labelAcl_name;
    private javax.swing.JTextField labelAuthors;
    private javax.swing.JTextField labelCheckout;
    private javax.swing.JTextField labelI_partition;
    private javax.swing.JTextField labelName;
    private javax.swing.JTextField labelOwner_name;
    private javax.swing.JTextField labelPathDocumentum;
    private javax.swing.JTextField labelPathSistema;
    private javax.swing.JTextField labelR_creation_date;
    private javax.swing.JTextField labelR_full_content_size;
    private javax.swing.JTextField labelR_modify_date;
    private javax.swing.JTextField labelR_object_id;
    private javax.swing.JTextField labelR_object_type;
    private javax.swing.JMenuItem opcionCopiar;
    private javax.swing.JPopupMenu popupEditar;
    // End of variables declaration//GEN-END:variables

    private void asignarIcono() {
        java.net.URL imgURL = PantallaPropiedades.class.getClassLoader().getResource("es/documentum/imagenes/si.png");
        Icon imgicon = new ImageIcon(imgURL);
        this.botonCerrar.setIcon(imgicon);

    }

    protected static Image getLogo() {
        //   java.net.URL imgURL = PantallaDocumentum.class.getClassLoader().getResource("es/documentum/imagenes/documentum_logo_mini.gif");
        java.net.URL imgURL = PantallaDocumentum.class.getClassLoader().getResource("es/documentum/imagenes/DCTM_32.png");

        if (imgURL != null) {
            return new ImageIcon(imgURL).getImage();
        } else {
            return null;
        }
    }

    public void consultarValores(String r_object_id) {
        this.setTitle("Propiedades del objeto - " + r_object_id);
        ArrayList<AtributosDocumentum> atributos = new ArrayList<>();
        atributos = docum.dameTodosAtributos(r_object_id);
        labelR_object_id.setText(r_object_id);
        for (int n = 0; n < atributos.size(); n++) {
            String valor = atributos.get(n).getNombre().toLowerCase();
            switch (valor) {
                case "object_name":
                    labelName.setText(atributos.get(n).getValor());
                    break;
                case "r_object_type":
                    labelR_object_type.setText(atributos.get(n).getValor());
                    break;
                case "r_full_content_size":
                    String tam = util.humanReadableByteCount(Long.parseLong(atributos.get(n).getValor()), false);
                    labelR_full_content_size.setText(tam);
                    break;
                case "acl_name":
                    labelAcl_name.setText(atributos.get(n).getValor());
                    break;
                case "i_partition":
                    labelI_partition.setText(atributos.get(n).getValor());
                    break;
                case "owner_name":
                    labelOwner_name.setText(atributos.get(n).getValor());
                    break;
                case "r_creation_date":
                    labelR_creation_date.setText(atributos.get(n).getValor());
                    break;
                case "r_modify_date":
                    labelR_modify_date.setText(atributos.get(n).getValor());
                    break;
                case "a_storage_type":
                    labelA_storage_type.setText(atributos.get(n).getValor());
                    break;
                case "a_content_type":
                    labelA_content_type.setText(atributos.get(n).getValor());
                    break;
                case "authors[0]":
                    labelAuthors.setText(atributos.get(n).getValor());
                    break;
            }

        }
        if (r_object_id.startsWith("09") || !labelA_storage_type.getText().isEmpty()) {
            labelPathSistema.setText(docum.ejecutarAPI("getpath,c," + r_object_id, "", docum.conectarDocumentum()));
        }
        labelPathDocumentum.setText(dameRutaId(r_object_id, docum.conectarDocumentum()));

        labelCheckout.setText(docum.estaCheckin(r_object_id) ? "N" : "S");

    }

    private String dameRutaId(String r_object_id, IDfSession sesion) {
        String ruta = "";
        IDfCollection colruta = docum.ejecutarDql("select r_folder_path from dm_folder_r where r_object_id in (select i_folder_id from dm_sysobject_r where i_position=-1 and r_object_id='" + r_object_id + "') and i_position=-1", sesion);
        if (colruta != null) {
            try {
                Boolean resp = colruta.next();
                IDfTypedObject rowruta = (IDfTypedObject) colruta.getTypedObject();
                ruta = rowruta.getValueAt(0).asString();
                colruta.close();
            } catch (DfException ex) {
                System.out.println("Error al recuperar la ruta al r_object_id " + r_object_id + " - " + ex.getMessage());
            }
        }
        return ruta;
    }

    private void popupmenu(MouseEvent evt) {
        if (evt.isPopupTrigger() || evt.getButton() == java.awt.event.MouseEvent.BUTTON3) {
            if (evt.getSource().getClass().getName().equals("javax.swing.JTextField")) {
                popupEditar.show(evt.getComponent(), evt.getX(), evt.getY());
                opcionCopiar.setEnabled(true);
            }
        }
    }

}
